# Generated by Django 5.2 on 2025-06-03 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopyrightRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('full_name', models.CharField(max_length=255, verbose_name='Контактное лицо')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('links_to_remove', models.TextField(help_text='Укажите одну или несколько ссылок, каждую с новой строки', verbose_name='Прямые ссылки на страницы ресурса, информация с которых подлежит удалению')),
                ('proof_document_url', models.URLField(help_text='Укажите ссылку на официальный документ (Google Drive, Dropbox и т.п.)', verbose_name='Ссылка на документ, подтверждающий исключительные права')),
                ('takedown_explanation_text', models.TextField(help_text='Этот текст будет отображаться пользователям на месте удалённого контента', verbose_name='Текст объяснения для пользователей')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='copyright_attachments/', verbose_name='Приложение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Запрос от правообладателя',
                'verbose_name_plural': 'Запросы от правообладателей',
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(choices=[('general', 'Общие вопросы'), ('playback', 'Проблемы с воспроизведением видео'), ('error', 'Сообщить об ошибке'), ('partnership', 'Сотрудничество'), ('ads', 'Реклама на сайте'), ('copyright', 'Жалоба от правообладателя'), ('account', 'Проблемы с аккаунтом'), ('other', 'Другое')], max_length=50, verbose_name='Тема обращения')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Обращение в поддержку',
                'verbose_name_plural': 'Обращения в поддержку',
            },
        ),
        migrations.CreateModel(
            name='CopyrightResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(verbose_name='Текст ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Ответ отправлен правообладателю')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='support.copyrightrequest', verbose_name='Запрос правообладателя')),
            ],
            options={
                'verbose_name': 'Ответ на запрос правообладателя',
                'verbose_name_plural': 'Ответы на запросы правообладателей',
            },
        ),
    ]
