# Generated by Django 5.2 on 2025-06-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='subject',
            field=models.CharField(choices=[('general', 'Общие вопросы'), ('playback', 'Проблемы с воспроизведением видео'), ('error', 'Сообщить об ошибке'), ('partnership', 'Сотрудничество'), ('ads', 'Реклама на сайте'), ('copyright', 'Жалоба от правообладателя'), ('account', 'Проблемы с аккаунтом'), ('comment', 'Жалоба на коментарий'), ('other', 'Другое')], max_length=50, verbose_name='Тема обращения'),
        ),
    ]
