# Generated by Django 5.2 on 2025-08-14 08:53

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_supportrequest_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_of_service', django_ckeditor_5.fields.CKEditor5Field(help_text='Пользовательское соглашение')),
                ('privacy_policy', django_ckeditor_5.fields.CKEditor5Field(help_text='Политика конфиденциальности')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
