# Generated by Django 5.2 on 2025-08-14 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_legal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legal',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='legal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
