# Generated by Django 5.2 on 2025-07-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0040_alter_media_avg_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка на публикацию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ManyToManyField(related_name='posts', to='film.media', verbose_name='Медиа')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
