# Generated by Django 5.2 on 2025-07-15 15:27

import telegrambot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_remove_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short',
            field=models.FileField(blank=True, null=True, upload_to=telegrambot.models.short_upload_to, verbose_name='Вертикальное видео (Short)'),
        ),
    ]
