# Generated by Django 5.2 on 2025-07-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0004_alter_post_options_remove_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.CharField(help_text='Уникальный ID для поиска', max_length=20, null=True),
        ),
    ]
