# Generated by Django 5.2 on 2025-07-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0006_alter_post_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uid',
            field=models.CharField(blank=True, help_text='Уникальный ID для поиска', max_length=20, unique=True),
        ),
    ]
