# Generated by Django 5.2 on 2025-06-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('media_id', models.CharField(blank=True, help_text='ID из API, если есть', max_length=255, null=True)),
                ('title', models.TextField(blank=True, help_text='Название медиа из API', null=True)),
                ('error_type', models.CharField(help_text='Тип ошибки: parsing, saving, network, etc.', max_length=100)),
                ('message', models.TextField(help_text='Описание ошибки')),
                ('raw_data', models.JSONField(blank=True, help_text='Исходный ответ/медиа-объект, если нужно', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
