# Generated by Django 5.2 on 2025-06-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0003_mediaimporterror'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='visitlog',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statify.visitlogtype'),
        ),
    ]
