# Generated by Django 5.2 on 2025-06-26 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0004_visitlogtype_visitlog_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Лог посещения', 'verbose_name_plural': 'Логи посещений'},
        ),
        migrations.AddField(
            model_name='visitlog',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Код HTTP-ответа (например, 200, 404)', null=True, verbose_name='HTTP статус'),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP-адрес клиента', null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='method',
            field=models.CharField(help_text='HTTP-метод запроса (GET, POST и т.п.)', max_length=10, verbose_name='Метод'),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='path',
            field=models.CharField(help_text='URL-путь, по которому был выполнен запрос', max_length=255, verbose_name='Путь'),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Время посещения', verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='type',
            field=models.ForeignKey(help_text='Категория визита (например, обычный, API-запрос и т.д.)', null=True, on_delete=django.db.models.deletion.CASCADE, to='statify.visitlogtype', verbose_name='Тип визита'),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Аутентифицированный пользователь, если есть', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Строка user-agent клиента', null=True, verbose_name='User Agent'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['timestamp'], name='statify_vis_timesta_fa4917_idx'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['path'], name='statify_vis_path_986c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['ip'], name='statify_vis_ip_5713a4_idx'),
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['status_code'], name='statify_vis_status__7d3027_idx'),
        ),
    ]
