# Generated by Django 5.2 on 2025-06-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0005_alter_visitlog_options_visitlog_status_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='country',
            field=models.CharField(blank=True, help_text='Двухбуквенный код страны посетителя по IP', max_length=2, null=True, verbose_name='Код страны'),
        ),
    ]
