# Generated by Django 5.2 on 2025-06-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0006_visitlog_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительная информация или комментарии к логу', null=True, verbose_name='Описание'),
        ),
    ]
