# Generated by Django 5.2 on 2025-06-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0007_visitlog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('next_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_load_all', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
