# Generated by Django 5.2 on 2025-07-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0008_mediaimportlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaimportlog',
            name='next_token',
        ),
    ]
