# Generated by Django 5.2 on 2025-07-01 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0029_media_rating_mpaa'),
        ('statify', '0009_remove_mediaimportlog_next_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaimportlog',
            options={},
        ),
        migrations.RemoveField(
            model_name='mediaimportlog',
            name='created_count',
        ),
        migrations.RemoveField(
            model_name='mediaimportlog',
            name='error_count',
        ),
        migrations.RemoveField(
            model_name='mediaimportlog',
            name='skipped_count',
        ),
        migrations.RemoveField(
            model_name='mediaimportlog',
            name='updated_count',
        ),
        migrations.CreateModel(
            name='MediaImportLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('skipped', 'Skipped'), ('error', 'Error')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='statify.mediaimportlog')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.media')),
            ],
        ),
    ]
