# Generated by Django 5.2 on 2025-07-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0010_alter_mediaimportlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimportlogentry',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('skipped', 'Skipped'), ('skipped_heavy', 'Skipped Heavy'), ('error', 'Error')], max_length=15),
        ),
    ]
