# Generated by Django 5.2 on 2025-07-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0011_alter_mediaimportlogentry_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimportlogentry',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('skipped', 'Skipped'), ('total', 'Total'), ('error', 'Error')], max_length=15),
        ),
    ]
