# Generated by Django 5.2 on 2025-07-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0012_alter_mediaimportlogentry_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimportlogentry',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('skipped', 'Skipped'), ('error', 'Error')], max_length=15),
        ),
        migrations.CreateModel(
            name='MediaImportLogTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.PositiveIntegerField(default=0)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total', to='statify.mediaimportlog')),
            ],
        ),
    ]
