# Generated by Django 5.2 on 2025-07-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0013_alter_mediaimportlogentry_action_mediaimportlogtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaimportlogtotal',
            name='temp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
