# Generated by Django 5.2 on 2025-07-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0041_alter_media_options'),
        ('statify', '0014_mediaimportlogtotal_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_logs', to='film.media'),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
