# Generated by Django 5.2 on 2025-07-15 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0041_alter_media_options'),
        ('statify', '0015_visitlog_media_visitlog_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visitlog',
            name='statify_vis_timesta_fa4917_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitlog',
            name='statify_vis_path_986c7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitlog',
            name='statify_vis_ip_5713a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitlog',
            name='statify_vis_status__7d3027_idx',
        ),
        migrations.AddIndex(
            model_name='visitlog',
            index=models.Index(fields=['path', 'session_key', 'timestamp', 'media'], name='statify_vis_path_b1bbad_idx'),
        ),
    ]
