# Generated by Django 5.2 on 2025-07-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0016_remove_visitlog_statify_vis_timesta_fa4917_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='protocol',
            field=models.CharField(blank=True, help_text='Версия HTTP-протокола (например, HTTP/1.1)', max_length=10, null=True, verbose_name='Протокол'),
        ),
    ]
