# Generated by Django 5.2 on 2025-07-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0017_visitlog_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlog',
            name='protocol',
            field=models.CharField(blank=True, default='HTTP/1.1', help_text='Версия HTTP-протокола (например, HTTP/1.1)', max_length=10, verbose_name='Протокол'),
        ),
    ]
