# Generated by Django 5.2 on 2025-07-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0018_alter_visitlog_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimportlogentry',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('skipped', 'Skipped'), ('media_error', 'MediaError'), ('error', 'Error')], max_length=15),
        ),
    ]
