# Generated by Django 5.2 on 2025-07-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statify', '0019_alter_mediaimportlogentry_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimportlogentry',
            name='action',
            field=models.CharField(choices=[('info', 'Info'), ('created', 'Created'), ('updated', 'Updated'), ('skipped', 'Skipped'), ('media_error', 'MediaError'), ('error', 'Error')], max_length=15),
        ),
    ]
