# Generated by Django 5.2 on 2025-06-09 08:41

import django.db.models.deletion
import film.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя актёра')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actors/', verbose_name='Фото')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Актёр',
                'verbose_name_plural': 'Актёры',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default=film.models.generate_unique_hash, editable=False, max_length=12, unique=True, verbose_name='Хеш')),
                ('name', models.CharField(max_length=255, verbose_name='Название подборки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('poster', models.ImageField(null=True, upload_to=film.models.collection_upload_to)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя режиссёра')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actors/', verbose_name='Фото')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код языка')),
                ('name', models.CharField(max_length=100, verbose_name='Название языка')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inId', models.CharField(max_length=1000, null=True)),
                ('hash', models.CharField(default=film.models.generate_unique_hash, editable=False, max_length=12, unique=True, verbose_name='Хеш')),
                ('name', models.CharField(max_length=1000, null=True, verbose_name='Название')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=film.models.poster_upload_to)),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
                ('imdb_rating', models.FloatField(blank=True, default=0, null=True, verbose_name='Рейтинг IMDb')),
                ('kinopoisk_rating', models.FloatField(blank=True, default=0, null=True, verbose_name='Рейтинг Кинопоиск')),
                ('minimal_age', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Возрастные ограничения')),
                ('type', models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал'), ('cartoon', 'cartoon'), ('cartoon-serial', 'cartoon-serial'), ('anime', 'anime')], default='series', max_length=14, verbose_name='Тип')),
                ('duration', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Продолжительность (мин)')),
                ('episodes_aired', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество уже вышедших эпизодов')),
                ('episodes_total', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество эпизодов')),
                ('allow_comments', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя персонажа')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='MediaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, null=True, verbose_name='Написать отзыв')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название трейлера')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на трейлер')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaVoiceover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_episodes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего эпизодов')),
                ('type', models.CharField(choices=[('voiceover', 'Озвучка'), ('subtitles', 'Субтитры')], default='series', help_text='Озвучка / Субтитры', max_length=10, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='MediaVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True, verbose_name='Название')),
                ('is_series', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название студии')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
            },
        ),
        migrations.CreateModel(
            name='TypeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True, verbose_name='Название')),
                ('is_series', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default=film.models.generate_unique_hash, editable=False, max_length=12, unique=True, verbose_name='Хеш')),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер эпизода')),
                ('season_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сезон')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'ordering': ['season_number', 'episode_number'],
            },
        ),
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('144p', '144p'), ('240p', '240p'), ('360p', '360p'), ('480p', 'SD (480p)'), ('720p', 'HD (720p)'), ('1080p', 'FHD (1080p)'), ('1440p', '2K (1440p)'), ('2160p', '4K (2160p)')], default='1080p', max_length=10)),
                ('file', models.FileField(blank=True, null=True, verbose_name='Видео файл')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
            ],
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voiceover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название студии')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Студия озвучки',
                'verbose_name_plural': 'Студии озвучки',
            },
        ),
        migrations.CreateModel(
            name='CollectionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='film.collection')),
            ],
        ),
    ]
