# Generated by Django 5.2 on 2025-06-09 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actor',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to='film.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='director',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directors', to='film.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='media',
            name='country',
            field=models.ManyToManyField(blank=True, related_name='media', to='film.country', verbose_name='Страны'),
        ),
        migrations.AddField(
            model_name='media',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='media', to='film.director', verbose_name='Режисёр'),
        ),
        migrations.AddField(
            model_name='media',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='media', to='film.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='media',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_media', to='film.media', verbose_name='Связанный объект'),
        ),
        migrations.AddField(
            model_name='collection',
            name='medias',
            field=models.ManyToManyField(related_name='collections', to='film.media'),
        ),
        migrations.AddField(
            model_name='mediacharacter',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='film.actor', verbose_name='Актёр'),
        ),
        migrations.AddField(
            model_name='mediacharacter',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='film.media', verbose_name='Фильм/Сериал'),
        ),
        migrations.AddField(
            model_name='mediacomment',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='film.media'),
        ),
        migrations.AddField(
            model_name='mediacomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='mediatrailer',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='film.media', verbose_name='Медиа'),
        ),
        migrations.AddField(
            model_name='mediavoiceover',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voiceovers', to='film.language', verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='mediavoiceover',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voiceovers', to='film.media'),
        ),
        migrations.AddField(
            model_name='mediavote',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='film.media'),
        ),
        migrations.AddField(
            model_name='mediavote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='voiceover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='film.mediavoiceover', verbose_name='Озвучка'),
        ),
        migrations.AddField(
            model_name='videosource',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='film.video'),
        ),
        migrations.AddField(
            model_name='videoview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoview',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_views', to='film.video'),
        ),
        migrations.AddField(
            model_name='mediavoiceover',
            name='voiceover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.voiceover', verbose_name='Озвучка'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionview',
            unique_together={('collection', 'user', 'session_key')},
        ),
        migrations.AlterUniqueTogether(
            name='mediavote',
            unique_together={('user', 'media')},
        ),
        migrations.AlterUniqueTogether(
            name='videosource',
            unique_together={('video', 'quality')},
        ),
    ]
