# Generated by Django 5.2 on 2025-06-12 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_mediaplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaplayer',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='film.media', verbose_name='Фильм/Сериал'),
        ),
    ]
