# Generated by Django 5.2 on 2025-06-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_mediaplayer_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='load',
            field=models.BooleanField(default=False),
        ),
    ]
