# Generated by Django 5.2 on 2025-06-14 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_country_load'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='voiceover',
        ),
        migrations.AlterField(
            model_name='videosource',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='film.media'),
        ),
        migrations.RemoveField(
            model_name='videoview',
            name='video',
        ),
        migrations.RemoveField(
            model_name='videoview',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='videosource',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='MediaView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_views', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='film.media')),
            ],
        ),
        migrations.DeleteModel(
            name='MediaVoiceover',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='VideoView',
        ),
        migrations.RemoveField(
            model_name='videosource',
            name='quality',
        ),
    ]
