# Generated by Django 5.2 on 2025-06-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_remove_video_voiceover_alter_videosource_video_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoSource',
        ),
    ]
