# Generated by Django 5.2 on 2025-06-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_remove_mediaview_video_media_views_mediaview_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='imdb_rating',
            field=models.FloatField(blank=True, default=0, verbose_name='Рейтинг IMDb'),
        ),
        migrations.AlterField(
            model_name='media',
            name='kinopoisk_rating',
            field=models.FloatField(blank=True, default=0, verbose_name='Рейтинг Кинопоиск'),
        ),
        migrations.AlterField(
            model_name='media',
            name='minimal_age',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Возрастные ограничения'),
        ),
    ]
