# Generated by Django 5.2 on 2025-06-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_alter_media_imdb_rating_alter_media_kinopoisk_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Продолжительность (мин)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='episodes_aired',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество уже вышедших эпизодов'),
        ),
        migrations.AlterField(
            model_name='media',
            name='episodes_total',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество эпизодов'),
        ),
    ]
