# Generated by Django 5.2 on 2025-06-14 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_alter_media_duration_alter_media_episodes_aired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='voiceover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='film.voiceover', verbose_name='Озвучка'),
        ),
    ]
