# Generated by Django 5.2 on 2025-06-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0011_media_voiceover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studio',
            new_name='ProductionStudio',
        ),
        migrations.DeleteModel(
            name='TypeMedia',
        ),
        migrations.AlterModelOptions(
            name='productionstudio',
            options={'verbose_name': 'Студия-производитель', 'verbose_name_plural': 'Студии-производители'},
        ),
    ]
