# Generated by Django 5.2 on 2025-06-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0012_rename_studio_productionstudio_delete_typemedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='voiceover_type',
            field=models.CharField(choices=[('voiceover', 'Озвучка'), ('subtitles', 'Субтитры')], default='subtitles', help_text='Озвучка / Субтитры', max_length=10, verbose_name='Тип'),
        ),
    ]
