# Generated by Django 5.2 on 2025-06-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0013_media_voiceover_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='hash',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='hash',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='productionstudio',
            name='hash',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='voiceover',
            name='hash',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
