# Generated by Django 5.2 on 2025-06-14 11:50

from django.db import migrations
import uuid


def generate_unique_hash():
    return uuid.uuid4().hex[:12]


def populate_hashes(apps, schema_editor):
    Actor = apps.get_model('film', 'Actor')
    Director = apps.get_model('film', 'Director')
    ProductionStudio = apps.get_model('film', 'ProductionStudio')
    Voiceover = apps.get_model('film', 'Voiceover')

    for Model in [Actor, Director, ProductionStudio, Voiceover]:
        existing_hashes = set()
        for obj in Model.objects.all():
            h = generate_unique_hash()
            while h in existing_hashes or Model.objects.filter(hash=h).exists():
                h = generate_unique_hash()
            obj.hash = h
            obj.save()
            existing_hashes.add(h)

class Migration(migrations.Migration):

    dependencies = [
        ('film', '0014_actor_hash_director_hash_productionstudio_hash_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_hashes),
    ]
