# Generated by Django 5.2 on 2025-06-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0015_auto_20250614_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='director',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='productionstudio',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='voiceover',
            name='hash',
        ),
    ]
