# Generated by Django 5.2 on 2025-06-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0016_remove_actor_hash_remove_director_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='hash',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='hash',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='productionstudio',
            name='hash',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='voiceover',
            name='hash',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
