# Generated by Django 5.2 on 2025-06-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0018_auto_20250614_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='hash',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='hash',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productionstudio',
            name='hash',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
