# Generated by Django 5.2 on 2025-06-14 13:38

import film.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0019_alter_actor_hash_alter_director_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='hash',
            field=models.CharField(default=film.models.generate_unique_hash, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='hash',
            field=models.CharField(default=film.models.generate_unique_hash, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='productionstudio',
            name='hash',
            field=models.CharField(default=film.models.generate_unique_hash, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='hash',
            field=models.CharField(default=film.models.generate_unique_hash, max_length=12, unique=True),
        ),
    ]
