# Generated by Django 5.2 on 2025-06-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0021_alter_actor_hash_alter_director_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='original_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название (Оригинал)'),
        ),
    ]
