# Generated by Django 5.2 on 2025-06-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0022_media_original_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='voiceover',
        ),
        migrations.AddField(
            model_name='media',
            name='voiceovers',
            field=models.ManyToManyField(null=True, related_name='media', to='film.voiceover', verbose_name='Озвучка'),
        ),
    ]
