# Generated by Django 5.2 on 2025-06-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0023_remove_media_voiceover_media_voiceovers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='voiceovers',
            field=models.ManyToManyField(blank=True, related_name='media', to='film.voiceover', verbose_name='Озвучка'),
        ),
    ]
