# Generated by Django 5.2 on 2025-06-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0024_alter_media_voiceovers'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
