# Generated by Django 5.2 on 2025-06-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0025_media_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='lgbt',
            field=models.BooleanField(default=False),
        ),
    ]
