# Generated by Django 5.2 on 2025-06-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0026_media_lgbt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='episodes_aired',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество уже вышедших эпизодов'),
        ),
        migrations.AlterField(
            model_name='media',
            name='episodes_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество эпизодов'),
        ),
        migrations.AlterField(
            model_name='media',
            name='imdb_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг IMDb'),
        ),
        migrations.AlterField(
            model_name='media',
            name='kinopoisk_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг Кинопоиск'),
        ),
        migrations.AlterField(
            model_name='media',
            name='minimal_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возрастные ограничения'),
        ),
    ]
