# Generated by Django 5.2 on 2025-06-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0027_alter_media_episodes_aired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('cartoon', 'cartoon'), ('cartoon-serial', 'cartoon-serial'), ('anime', 'anime'), ('movie', 'Фильм'), ('series', 'Сериал')], default='series', max_length=14, verbose_name='Тип'),
        ),
    ]
