# Generated by Django 5.2 on 2025-06-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0028_alter_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='rating_mpaa',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('R+', 'R+'), ('Rx', 'Rx')], default='G', max_length=14, verbose_name='Рейтинг MPAA'),
        ),
    ]
