# Generated by Django 5.2 on 2025-07-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0030_alter_media_rating_mpaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='inId',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
    ]
