# Generated by Django 5.2 on 2025-07-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0031_alter_media_inid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Имя актёра'),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя режиссёра'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название языка'),
        ),
    ]
