# Generated by Django 5.2 on 2025-07-03 19:10

from django.db import migrations


def delete_duplicate_media(apps, schema_editor):
    Media = apps.get_model('film', 'Media')
    MediaView = apps.get_model('film', 'MediaView')

    from django.db.models import Count

    duplicates = (
        Media.objects
        .values('name')
        .annotate(name_count=Count('id'))
        .filter(name_count__gt=1)
    )

    for entry in duplicates:
        name = entry['name']
        media_qs = Media.objects.filter(name=name).annotate(view_count=Count('media_views'))

        # Сохраняем только одну запись, остальные — удалим, если у них нет MediaView
        media_to_keep = media_qs.order_by('-view_count', '-poster').first()
        for media in media_qs.exclude(pk=media_to_keep.pk):
            media.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0032_alter_actor_name_alter_director_name_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_media),
    ]
