# Generated by Django 5.2 on 2025-07-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0033_remove_duplicate_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(max_length=1000, null=True, unique=True, verbose_name='Название'),
        ),
    ]
