# Generated by Django 5.2 on 2025-07-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0034_alter_media_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description_modified',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание (изменённое)'),
        ),
    ]
