# Generated by Django 5.2 on 2025-07-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0035_media_description_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='rating_mpaa',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('R+', 'R+'), ('Rx', 'Rx')], max_length=15, null=True, verbose_name='Рейтинг MPAA'),
        ),
    ]
