# Generated by Django 5.2 on 2025-07-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0036_alter_media_rating_mpaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='rating_mpaa',
            field=models.CharField(choices=[('G', 'Для всех возрастов (G)'), ('PG', 'С родителями желательно (PG)'), ('PG-13', 'До 13 лет нежелательно (PG-13)'), ('R', 'До 17 лет с родителями (R)'), ('R+', 'Только взрослым (R+)'), ('Rx', 'Ограничено (Rx)')], max_length=15, null=True, verbose_name='Рейтинг MPAA'),
        ),
    ]
