# Generated by Django 5.2 on 2025-07-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0037_alter_media_rating_mpaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
