# Generated by Django 5.2 on 2025-07-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0038_media_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
