# Generated by Django 5.2 on 2025-07-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0040_alter_media_avg_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['name']},
        ),
    ]
