# Generated by Django 5.2 on 2025-07-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0041_alter_media_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='country',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='media', to='film.country', verbose_name='Страны'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description_modified',
            field=models.TextField(blank=True, db_index=True, max_length=5000, null=True, verbose_name='Описание (изменённое)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='director',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='media', to='film.director', verbose_name='Режисёр'),
        ),
        migrations.AlterField(
            model_name='media',
            name='genres',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='media', to='film.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='media',
            name='original_name',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='Название (Оригинал)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='release_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('cartoon', 'cartoon'), ('cartoon-serial', 'cartoon-serial'), ('anime', 'anime'), ('movie', 'Фильм'), ('series', 'Сериал')], db_index=True, default='series', max_length=14, verbose_name='Тип'),
        ),
    ]
