# Generated by Django 5.2 on 2025-07-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0042_alter_media_country_alter_media_description_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='avg_rating',
            field=models.FloatField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='imdb_rating',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Рейтинг IMDb'),
        ),
        migrations.AlterField(
            model_name='media',
            name='kinopoisk_rating',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Рейтинг Кинопоиск'),
        ),
    ]
