# Generated by Django 5.2 on 2025-08-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0043_alter_media_avg_rating_alter_media_imdb_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaView',
        ),
    ]
