# Generated by Django 5.2 on 2025-08-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0044_delete_mediaview'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название страны'),
        ),
    ]
